"""Native W4A4 grouped routed-expert GEMM for the PREFILL path (exp-0015a).

Vehicle: the CUTLASS CuTe-DSL scaled grouped GEMM for MoE (vendored under
engine/pyengine/vendor/cutlass_moe/, BSD-3; upstream examples/python/CuTeDSL/
cute/blackwell/kernel/moe/torch_scaled_grouped_mm.py) — warp-specialized
tcgen05.mma.block_scale NVFP4xNVFP4 with a per-expert global-scale multiply
in the epilogue. Exact-validated on this node's GPU 4 at our shape class
(E=256, top6, hidden 6144; DEADENDS 2026-07-30 exp-0015 addendum 3) in the
configuration used here verbatim: tiles (128,128,128), cluster (1,1,1),
dynamic expert count, separate_tensormap_init, consistent_token_padding
False.

Why (exp-0015 groundwork): the W4A16 Triton GEMM (kernels/moe_gemm.py) pays
an in-register convert-ALU floor (~2.5 cvt-class ops/element, exp-0010) that
puts prefill's dominant kernel ~5.7x off roofline; native FP4 MMA deletes
the convert pipe (measured 0.053 ms vs 13.5 ms for a T=736 layer's w13
class, arm A). W4A4 on these layers is the REFERENCE'S OWN numeric recipe
(vLLM ModelOpt fused MoE quantizes activations with input_scale =
input_amax/(448*6); the D11 goldens / D13 envelope were generated by that
path), so adopting it moves the engine TOWARD the goldens (arm J: today's
passing W4A16 already carries the full A16-vs-A4 systematic difference).

Layout notes (all zero-copy on the checkpoint tensors):
- B: pack.packed [E, N, K/2] uint8 viewed float4_e2m1fn_x2 + transpose(1,2)
  = the torch scaled_grouped_mm (E, K, N) K-stride-1 fp4 layout the kernel
  expects. w13's interleaved [g0,u0,..] rows simply make the OUTPUT columns
  interleaved; the silu epilogue reads them via strided views.
- SFB: checkpoint .scale [E, N, K/16] e4m3 repacked ONCE per layer into the
  Blackwell 32_4_4 blocked swizzle, all experts in one permute (bitwise the
  example's per-expert to_blocked; t_moe_w4a4 arm a). Kept alongside the
  original .scale (the graphed decode W4A16 kernels still read that form).
- A/SFA: every expert group is padded to a 128-row multiple in the pair-row
  space (offs are 128-aligned). Zero GEMM cost — tile count ceil(rows/128)
  is unchanged — and the per-group swizzle the kernel expects becomes
  exactly the global swizzle kernels/fp4_quant.py emits, avoiding the
  example's unexercised non-16-multiple group path entirely.
- alpha: the kernel's per-expert epilogue computes global_scale_a[e] *
  global_scale_b[e] = input_scale * weight_scale2 (fp32) before the bf16
  store — the product _scaled_mm could not express (DEADENDS risk (c)).

Numerics (D13-envelope semantics): activation quant is recipe-exact via
hardware RTNE converts (kernels/fp4_quant.py, bitwise-validated); the
inter-GEMM silu chain and the post-GEMM routing-weight epilogue mirror the
eager rounding chain of kernels/moe_gemm.py op for op; the final per-token
slot reduction is the same fp32-accumulated sum. Remaining drift = fp32
accumulation order inside the MMA vs the Triton tile loop — the drift class
the D13 envelope covers.
Determinism (t_b3-adapted worker arm): stable sort, exact-integer bincount/
cumsum, fixed grids, static tile scheduler, no atomics, each output row
written exactly once; pad rows are exact zeros end to end, and slack rows
beyond offs[-1] are never read by any consumer. Two runs of the same
schedule are bitwise identical (t_moe_w4a4 arm d)."""
import torch

import cuda.bindings.driver as cuda_drv
import cutlass
import cutlass.cute as cute
import cutlass.torch as cutlass_torch
import cutlass.utils as utils

from engine.pyengine.vendor.cutlass_moe.torch_scaled_grouped_mm import (
    ScaledGroupedGemmKernel,
)
from engine.pyengine.kernels.fp4_quant import nvfp4_quant, nvfp4_quant_scatter

#launch config, fixed (no autotune: deterministic, one JIT specialization) —
#the exact configuration the GPU-4 validation ran (DEADENDS addendum 3)
MMA_TILER = (128, 128, 128)
CLUSTER = (1, 1, 1)

_KERNELS = {}   # (device_index, K_logical, N) -> {"compiled", "ws"}
_MAC = {}       # device_index -> max_active_clusters


def _to_cute(t):
    ct = cutlass_torch.from_dlpack(t)
    return ct.mark_layout_dynamic(leading_dim=cutlass_torch.get_leading_dim(t))


def _run_gemm(k_logical, n, a_pk, sfa2d, b_c, sfb_c, c, offs, gsa_c, gsb_c):
    """One grouped blockscaled GEMM: A [M_pad, K/2] u8 + SFA (2D swizzled)
    x prepped B/SFB/global-scale cute tensors -> C [M_pad, n] bf16. Compiles
    once per (device, K, N) — layout-dynamic leading dims make the artifact
    reusable across M_pad/routings — then replays the compiled kernel."""
    dev = c.device
    e_cnt = offs.shape[0]
    with torch.cuda.device(dev):
        stream = cuda_drv.CUstream(torch.cuda.current_stream().cuda_stream)
        a_c = _to_cute(a_pk.view(torch.float4_e2m1fn_x2))
        sfa_c = _to_cute(sfa2d)
        c_c = _to_cute(c)
        offs_c = _to_cute(offs)
        key = (dev.index, k_logical, n)
        ent = _KERNELS.get(key)
        if ent is None:
            kern = ScaledGroupedGemmKernel(
                scenario="2Dx3D", sf_vec_size=16, accumulate_on_output=False,
                separate_tensormap_init=True, consistent_token_padding=False,
                acc_dtype=cutlass.Float32, mma_tiler_mnk=MMA_TILER,
                cluster_shape_mnk=CLUSTER, use_2cta_instrs=False,
                fixed_expert_cnt=None)
            ws = torch.full((kern.get_workspace_size(e_cnt),), 255,
                            dtype=torch.uint8, device=dev)
            if dev.index not in _MAC:
                _MAC[dev.index] = utils.HardwareInfo().get_max_active_clusters(
                    CLUSTER[0] * CLUSTER[1])
            compiled = cute.compile(
                kern, a_c, b_c, sfa_c, sfb_c, c_c, offs_c, _to_cute(ws),
                _MAC[dev.index], stream,
                global_scale_a=gsa_c, global_scale_b=gsb_c)
            ent = {"compiled": compiled, "ws": ws}
            _KERNELS[key] = ent
        ent["compiled"](a_c, b_c, sfa_c, sfb_c, c_c, offs_c,
                        _to_cute(ent["ws"]), stream,
                        global_scale_a=gsa_c, global_scale_b=gsb_c)


def _sfb_blocked(scale):
    """Checkpoint block scales (E, N, K/16) e4m3 -> (E, N*K/16) with each
    expert's matrix in the 32_4_4 blocked swizzle, all experts in one
    permute. Bitwise the example's stacked per-expert to_blocked (row block
    r of 128 splits (4,32) as g4=r//32, g32=r%32; order rb, cb, g32, g4, c)."""
    E, N, kg = scale.shape
    assert N % 128 == 0 and kg % 4 == 0
    u = scale.view(torch.uint8)
    u = u.reshape(E, N // 128, 4, 32, kg // 4, 4)
    u = u.permute(0, 1, 4, 3, 2, 5)
    return u.reshape(E, N * kg).contiguous().view(torch.float8_e4m3fn)


class _Prep:
    """Per-layer one-time W4A4 form of a (pack13, pack2) pair: fp4 B views,
    swizzled SFB, per-expert global-scale vectors, activation input scales."""

    def __init__(self, pack13, pack2):
        F8_MAX = 448.0
        self.gs13 = float(pack13.input_amax) / (F8_MAX * 6.0)
        self.gs2 = float(pack2.input_amax) / (F8_MAX * 6.0)
        dev = pack13.packed.device
        E = pack13.packed.shape[0]
        #keep the torch views alive for the cute tensors' lifetime
        self._b13_t = pack13.packed.view(torch.float4_e2m1fn_x2).transpose(1, 2)
        self._b2_t = pack2.packed.view(torch.float4_e2m1fn_x2).transpose(1, 2)
        self.b13 = _to_cute(self._b13_t)
        self.b2 = _to_cute(self._b2_t)
        self.sfb13 = _sfb_blocked(pack13.scale)
        self.sfb2 = _sfb_blocked(pack2.scale)
        self.sfb13_c = _to_cute(self.sfb13)
        self.sfb2_c = _to_cute(self.sfb2)
        self.gsa13 = torch.full((E,), self.gs13, dtype=torch.float32,
                                device=dev)
        self.gsa2 = torch.full((E,), self.gs2, dtype=torch.float32,
                               device=dev)
        self.gsa13_c = _to_cute(self.gsa13)
        self.gsa2_c = _to_cute(self.gsa2)
        self.gsb13_c = _to_cute(pack13.scale2)
        self.gsb2_c = _to_cute(pack2.scale2)


def _prep(pack13, pack2):
    p = getattr(pack13, "_w4a4", None)
    if p is None:
        p = _Prep(pack13, pack2)
        pack13._w4a4 = p
    return p


def moe_experts_w4a4(x, pack13, pack2, topk_indices, topk_weights):
    """Grouped W4A4 drop-in for model.moe_experts on the prefill path when
    the routed experts are loader.PackedExperts with input_amax. x [T,
    hidden] bf16; returns [T, hidden] bf16 — same contract and same final
    fp32-accumulated slot reduction as moe_experts_packed."""
    T, K = x.shape
    top_k = topk_indices.shape[1]
    E = pack13.packed.shape[0]
    ffn = pack13.packed.shape[1] // 2
    assert pack13.deinterleave and not pack2.deinterleave
    prep = _prep(pack13, pack2)
    dev = x.device

    #1. pair list sorted by expert id (stable -> deterministic) and the
    #   128-padded per-expert row space: offs 128-aligned end offsets,
    #   dst = each real pair row's slot in the padded space
    flat = topk_indices.reshape(-1)
    P = flat.shape[0]
    sorted_e, perm = torch.sort(flat, stable=True)
    cnt = torch.bincount(sorted_e, minlength=E)
    pad_cnt = ((cnt + 127) // 128) * 128
    ends = torch.cumsum(pad_cnt, 0)
    offs = ends.to(torch.int32)
    starts_pad = ends - pad_cnt
    starts_real = torch.cumsum(cnt, 0) - cnt
    rank = torch.arange(P, device=dev) - starts_real[sorted_e]
    dst = (starts_pad[sorted_e] + rank).to(torch.int32)
    src = (perm // top_k).to(torch.int32)
    #   host-side capacity bound >= offs[-1] (no device sync):
    #   sum(round_up(c,128)) <= P + 127 * #nonzero-groups
    m_cap = (P + 127 * min(E, P) + 127) // 128 * 128

    #2. gate/up: quant-scatter x rows into the padded space, grouped GEMM
    #   (alpha = input_scale*scale2 in-kernel), silu*up mirroring the eager
    #   rounding chain (interleaved rows -> interleaved output columns)
    a1, sfa1 = nvfp4_quant_scatter(x, src, dst, m_cap, prep.gs13)
    c1 = torch.empty(m_cap, 2 * ffn, device=dev, dtype=torch.bfloat16)
    _run_gemm(K, 2 * ffn, a1, sfa1.view(m_cap, K // 16), prep.b13,
              prep.sfb13_c, c1, offs, prep.gsa13_c, prep.gsb13_c)
    gu = c1.view(m_cap, ffn, 2)
    g = gu[..., 0].float()
    u = gu[..., 1].float()
    act = ((g * torch.sigmoid(g)).to(torch.bfloat16).float()
           * u).to(torch.bfloat16).contiguous()

    #3. down: re-quant the activations (w2's own input_scale), grouped GEMM
    a2, sfa2 = nvfp4_quant(act, prep.gs2)
    c2 = torch.empty(m_cap, K, device=dev, dtype=torch.bfloat16)
    _run_gemm(ffn, K, a2, sfa2.view(m_cap, ffn // 16), prep.b2,
              prep.sfb2_c, c2, offs, prep.gsa2_c, prep.gsb2_c)

    #4. routing-weight epilogue (eager chain: bf16 store * wt at fp32
    #   opmath -> bf16), un-permute, fp32-accumulated slot reduction
    wt = topk_weights.reshape(-1)[perm]
    vals = (c2.index_select(0, dst.long()).float()
            * wt.float()[:, None]).to(torch.bfloat16)
    out_pairs = torch.empty(P, K, device=dev, dtype=torch.bfloat16)
    out_pairs[perm] = vals
    return out_pairs.view(T, top_k, K).sum(dim=1)
