"""
@brief  Correctness gate: compares the candidate engine (OpenAI-compatible
        endpoint) against the committed GOLDENS for Inkling. An experiment
        that fails here never reaches perf.

        Reference = goldens/goldens_parity.json (decision D11): generated by
        the PINNED vLLM build under VLLM_BATCH_INVARIANT=1 (deterministic;
        verified 0/50 diff on re-run). The former HF-transformers reference
        was retired after its loader was shown to corrupt grouped-fp4 expert
        weights (docs/logs/, probe runs 2026-07-24/25). Candidates must run
        their own deterministic mode when facing this gate.

        Two checks, in order of strictness:
          1. Greedy token match  — temperature 0, exact token-id agreement
                                   for the first N generated tokens.
          2. Logprob parity      — max |delta| of top-1 logprobs within a
                                   bf16-appropriate tolerance.
"""
import json
import argparse
import hashlib
import pathlib
import requests

# tolerance chosen for bf16 accumulation differences; tighten to 5e-3 once
# the engine is stable, loosen ONLY with a written justification in the ledger
LOGPROB_TOL = 2e-2
GREEDY_TOKENS = 64

PROMPTS_PATH = "configs/parity_prompts.json"   # ~50 diverse prompts, fixed forever
GOLDENS_PATH = "goldens/goldens_parity.json"   # committed reference (D11)


def load_goldens(prompts: list[str], max_new: int):
    """
    @brief  Load the committed goldens as the reference side of the gate.
            Fails loudly on any integrity problem — a gate with a drifted
            reference is worse than no gate.
    @return list of (token_ids, logprobs) per prompt, aligned with `prompts`
    """
    #1. existence + parse
    p = pathlib.Path(GOLDENS_PATH)
    if not p.exists():
        raise RuntimeError(f"goldens missing at {GOLDENS_PATH} — run "
                           f"scripts/generate_goldens.py against the goldens-"
                           f"mode server (see D11) and commit the result")
    g = json.loads(p.read_text())
    meta, items = g["meta"], g["items"]

    #2. integrity: the goldens must cover exactly these prompts, in order,
    #   at at least this depth
    if len(items) != len(prompts):
        raise RuntimeError(f"goldens cover {len(items)} prompts, gate needs "
                           f"{len(prompts)} — regenerate")
    for i, (it, pr) in enumerate(zip(items, prompts)):
        if it["prompt"] != pr:
            raise RuntimeError(f"goldens prompt {i} differs from "
                               f"{PROMPTS_PATH} — prompt set drifted; "
                               f"regenerate goldens or restore prompts")
        if len(it["token_ids"]) < max_new and it.get("finish_reason") == "length":
            raise RuntimeError(f"goldens prompt {i} has only "
                               f"{len(it['token_ids'])} tokens < {max_new}")

    #3. provenance echo (lands in worker logs; auditors grep for this)
    print(f"[gate] reference: goldens sha={meta.get('goldens_sha','?')} "
          f"fingerprint={meta.get('system_fingerprint','?')} "
          f"cache_key={meta.get('cache_key','?')}")
    return [(it["token_ids"][:max_new], it["token_logprobs"][:max_new])
            for it in items]


def candidate_greedy(endpoint: str, model: str, prompts: list[str], max_new: int):
    """
    @brief  Same generation through the engine under test via /v1/completions.
    """
    out = []
    for p in prompts:
        r = requests.post(
            f"{endpoint}/v1/completions",
            json={
                "model": model,
                "prompt": p,
                "max_tokens": max_new,
                "temperature": 0,
                "logprobs": 1,
                "seed": 0,
                "return_token_ids": True,
            },
            timeout=300,
        )
        r.raise_for_status()
        choice = r.json()["choices"][0]
        #1. token_ids is at CHOICE level (requires "return_token_ids": true);
        #   fail loudly if absent — silent fallback to strings would compare
        #   strings vs reference IDs and fail every prompt
        ids = choice.get("token_ids")
        if ids is None:
            raise RuntimeError(
                "engine did not return token_ids — check return_token_ids support")
        lps = choice["logprobs"]["token_logprobs"]
        out.append((ids, lps))
    return out


def run_gate(endpoint: str, model: str):
    """
    @return (parity_pass: bool, max_logprob_delta: float, detail: dict)
    """
    prompts = json.load(open(PROMPTS_PATH))
    if isinstance(prompts, dict):
        prompts = prompts["prompts"]

    ref = load_goldens(prompts, GREEDY_TOKENS)
    cand = candidate_greedy(endpoint, model, prompts, GREEDY_TOKENS)

    max_delta, mismatches, first_divergences = 0.0, 0, []
    for i, ((r_ids, r_lp), (c_ids, c_lp)) in enumerate(zip(ref, cand)):
        #1. token-id agreement is the hard requirement (compare to the
        #   shorter of the two in case the candidate stopped at eos exactly
        #   where the goldens did)
        n = min(len(r_ids), len(c_ids))
        if list(r_ids)[:n] != list(c_ids)[:n]:
            mismatches += 1
            k = next(j for j in range(n) if r_ids[j] != c_ids[j])
            first_divergences.append(
                {"prompt": i, "pos": k,
                 "golden_id": r_ids[k], "candidate_id": c_ids[k],
                 "golden_lp": r_lp[k] if k < len(r_lp) else None})
            continue
        #2. logprob drift is the soft requirement, tracked as max |delta|
        for a, b in zip(r_lp, c_lp):
            if a is None or b is None:
                continue
            max_delta = max(max_delta, abs(a - b))

    passed = mismatches == 0 and max_delta <= LOGPROB_TOL
    return passed, max_delta, {
        "prompt_mismatches": mismatches,
        "n_prompts": len(prompts),
        "first_divergences": first_divergences[:5],
    }


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--endpoint", required=True)
    ap.add_argument("--model", default="/workspace/models/inkling-nvfp4")
    args = ap.parse_args()

    ok, delta, detail = run_gate(args.endpoint, args.model)
    print(json.dumps({"parity_pass": ok, "max_logprob_delta": delta, **detail}))
    raise SystemExit(0 if ok else 1)