"""
@brief  Correctness gate: compares the candidate engine (OpenAI-compatible
        endpoint) against the committed GOLDENS for Inkling. An experiment
        that fails here never reaches perf.

        Reference = goldens/goldens_parity.json (D11): generated by the
        PINNED vLLM build under VLLM_BATCH_INVARIANT=1 (deterministic;
        0/50 re-run diff). Two modes:

        FREE-RUN (default): 64-token greedy trajectories, exact token match
        + logprob tolerance. Per D13 this mode is the gate for DETERMINISTIC
        SELF-CONSISTENCY (an engine vs goldens cut from ITSELF under its
        deterministic mode). It is NOT attainable cross-implementation:
        measured 2026-07-27, bench-mode vLLM itself scores 45/50 mismatches
        / max delta 0.583 against these goldens (near-tie flips compound
        over 64 steps; evidence docs/logs/gate_vs_benchvllm_*.log).

        TEACHER-FORCED (--teacher-forced; D13, HUMAN RULING 2026-07-27):
        the cross-implementation parity gate. For K evenly-spaced positions
        per prompt, feed prompt + golden_ids[:p] and compare the candidate's
        1-token greedy prediction against golden_ids[p]. No divergence
        compounding — per-step distributional agreement everywhere. Arms:
          (a) top-1 agreement rate with the golden token;
          (b) |logprob delta| on agreeing steps.
        PASS is calibrated, not absolute: --envelope <file> loads the same
        protocol's result measured against the PINNED BENCH-MODE vLLM (the
        reference engine's own cross-kernel-mode variance); the candidate
        passes iff agreement >= envelope - 2pts AND mean delta <= envelope
        x 1.25. An engine indistinguishable from vLLM's own mode-to-mode
        variance is at parity with vLLM.
"""
import json
import argparse
import pathlib
import statistics
import requests

LOGPROB_TOL = 2e-2
GREEDY_TOKENS = 64

PROMPTS_PATH = "configs/parity_prompts.json"
GOLDENS_PATH = "goldens/goldens_parity.json"


def load_goldens(prompts: list[str], max_new: int):
    """
    @brief  Load the committed goldens as the reference side of the gate.
            Fails loudly on any integrity problem.
    """
    p = pathlib.Path(GOLDENS_PATH)
    if not p.exists():
        raise RuntimeError(f"goldens missing at {GOLDENS_PATH} — run "
                           f"scripts/generate_goldens.py (goldens-mode server, D11)")
    g = json.loads(p.read_text())
    meta, items = g["meta"], g["items"]
    if len(items) != len(prompts):
        raise RuntimeError(f"goldens cover {len(items)} prompts, gate needs "
                           f"{len(prompts)} — regenerate")
    for i, (it, pr) in enumerate(zip(items, prompts)):
        if it["prompt"] != pr:
            raise RuntimeError(f"goldens prompt {i} differs from {PROMPTS_PATH}")
        if len(it["token_ids"]) < max_new and it.get("finish_reason") == "length":
            raise RuntimeError(f"goldens prompt {i}: only {len(it['token_ids'])} tokens")
    print(f"[gate] reference: goldens sha={meta.get('goldens_sha','?')} "
          f"fingerprint={meta.get('system_fingerprint','?')} "
          f"cache_key={meta.get('cache_key','?')}")
    return [(it["token_ids"][:max_new], it["token_logprobs"][:max_new])
            for it in items]


def _post(endpoint, payload):
    r = requests.post(f"{endpoint}/v1/completions", json=payload, timeout=300)
    r.raise_for_status()
    choice = r.json()["choices"][0]
    ids = choice.get("token_ids")
    if ids is None:
        raise RuntimeError("engine did not return token_ids — check "
                           "return_token_ids support")
    return ids, choice["logprobs"]["token_logprobs"]


def candidate_greedy(endpoint: str, model: str, prompts: list[str], max_new: int):
    """
    @brief  Free-run generation through the engine under test.
    """
    out = []
    for p in prompts:
        out.append(_post(endpoint, {
            "model": model, "prompt": p, "max_tokens": max_new,
            "temperature": 0, "logprobs": 1, "seed": 0,
            "return_token_ids": True}))
    return out


def run_gate(endpoint: str, model: str):
    """
    @brief  FREE-RUN mode (deterministic self-consistency, per D13).
    @return (parity_pass, max_logprob_delta, detail)
    """
    prompts = json.load(open(PROMPTS_PATH))
    if isinstance(prompts, dict):
        prompts = prompts["prompts"]
    ref = load_goldens(prompts, GREEDY_TOKENS)
    cand = candidate_greedy(endpoint, model, prompts, GREEDY_TOKENS)

    max_delta, mismatches, first_divergences = 0.0, 0, []
    for i, ((r_ids, r_lp), (c_ids, c_lp)) in enumerate(zip(ref, cand)):
        n = min(len(r_ids), len(c_ids))
        if list(r_ids)[:n] != list(c_ids)[:n]:
            mismatches += 1
            k = next(j for j in range(n) if r_ids[j] != c_ids[j])
            first_divergences.append(
                {"prompt": i, "pos": k, "golden_id": r_ids[k],
                 "candidate_id": c_ids[k],
                 "golden_lp": r_lp[k] if k < len(r_lp) else None})
            continue
        for a, b in zip(r_lp, c_lp):
            if a is None or b is None:
                continue
            max_delta = max(max_delta, abs(a - b))
    passed = mismatches == 0 and max_delta <= LOGPROB_TOL
    return passed, max_delta, {"mode": "free-run",
                               "prompt_mismatches": mismatches,
                               "n_prompts": len(prompts),
                               "first_divergences": first_divergences[:5]}


def run_teacher_forced(endpoint: str, model: str, model_dir: str, k: int):
    """
    @brief  TEACHER-FORCED mode (cross-implementation parity, D13).
            Prompts are sent as TOKEN-ID arrays (prompt ids + golden prefix)
            so no detokenize/retokenize boundary effects exist.
    @return result dict (agree_rate, deltas, per-position diagnostics)
    """
    #1. local tokenizer = the exact artifact both engines load (proven
    #   identical vs vLLM /tokenize 0/50, B3.5 note)
    from transformers import AutoTokenizer
    tok = AutoTokenizer.from_pretrained(model_dir, trust_remote_code=True)

    prompts = json.load(open(PROMPTS_PATH))
    if isinstance(prompts, dict):
        prompts = prompts["prompts"]
    ref = load_goldens(prompts, GREEDY_TOKENS)

    agree, total, deltas, disagreements = 0, 0, [], []
    for i, (p, (g_ids, g_lp)) in enumerate(zip(prompts, ref)):
        p_ids = tok(p).input_ids
        #2. K evenly-spaced golden positions in [0, len-1]
        n = len(g_ids)
        positions = sorted(set(round(j * (n - 1) / max(k - 1, 1)) for j in range(k)))
        for pos in positions:
            ids, lps = _post(endpoint, {
                "model": model, "prompt": p_ids + list(g_ids[:pos]),
                "max_tokens": 1, "temperature": 0, "logprobs": 1,
                "seed": 0, "return_token_ids": True})
            total += 1
            if ids[0] == g_ids[pos]:
                agree += 1
                if g_lp[pos] is not None and lps[0] is not None:
                    deltas.append(abs(g_lp[pos] - lps[0]))
            else:
                disagreements.append({"prompt": i, "pos": pos,
                                      "golden_id": g_ids[pos],
                                      "candidate_id": ids[0],
                                      "golden_lp": g_lp[pos]})
        print(f"[gate-tf] prompt {i+1}/{len(prompts)}: "
              f"agree {agree}/{total} so far", flush=True)

    return {"mode": "teacher-forced", "k_per_prompt": k,
            "n_comparisons": total,
            "agree": agree, "agree_rate": round(agree / total, 4),
            "delta_mean": round(statistics.mean(deltas), 6) if deltas else None,
            "delta_max": round(max(deltas), 6) if deltas else None,
            "disagreements_sample": disagreements[:10]}


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--endpoint", required=True)
    ap.add_argument("--model", default="/workspace/models/inkling-nvfp4")
    ap.add_argument("--teacher-forced", action="store_true",
                    help="D13 cross-implementation parity mode")
    ap.add_argument("--tf-positions", type=int, default=16,
                    help="teacher-forced positions per prompt")
    ap.add_argument("--envelope", default=None,
                    help="JSON result of this protocol vs bench-mode vLLM; "
                         "sets the D13 pass envelope")
    args = ap.parse_args()

    if args.teacher_forced:
        res = run_teacher_forced(args.endpoint, args.model, args.model,
                                 args.tf_positions)
        verdict = {"parity_pass": None, **res}
        if args.envelope:
            env = json.loads(pathlib.Path(args.envelope).read_text())
            #3. D13 pass rule: within the reference engine's own
            #   cross-kernel-mode variance (slack documented in header)
            ok = (res["agree_rate"] >= env["agree_rate"] - 0.02 and
                  (res["delta_mean"] or 0) <= (env["delta_mean"] or 0) * 1.25)
            verdict["parity_pass"] = ok
            verdict["envelope"] = {"agree_rate": env["agree_rate"],
                                   "delta_mean": env["delta_mean"],
                                   "source": args.envelope}
        print(json.dumps(verdict))
        raise SystemExit(0 if verdict["parity_pass"] else
                         (0 if verdict["parity_pass"] is None else 1))
    else:
        ok, delta, detail = run_gate(args.endpoint, args.model)
        print(json.dumps({"parity_pass": ok, "max_logprob_delta": delta,
                          **detail}))
        raise SystemExit(0 if ok else 1)